services:
  frontend:
    container_name: hapiss-dev
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - hapiss-network

networks:
  hapiss-network:
    name: hapiss-network
    driver: bridge
    external: true
